use_frameworks!

platform :ios, '9.0'

target 'SuperPopup_Example' do
  pod 'SuperPopup', :path => '../'

  target 'SuperPopup_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
